### ISSUE TITLE
Kontrola hodnoty

### ISSUE THREAD

**Issue by sparkcz** [Lossik/mikrotik-api#1]
Ahoj,
pridej sem prosim kontrolu na is_string($value), haze to pak chyby, kdyz je hodnota cokoliv jineho nez string. Diky.

https://github.com/Lossik/mikrotik-api/blob/d14ebc273b17a54841f10fc5289f9d82826f0a07/src/Command.php#L156

**Comment by Lossik** [comment]
upraveno v nove verzi
